version: '3.1'

services:
  db:
    container_name: ${POSTGRES_DB}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8080:5432
    volumes:
      - db:/.docker/var/lib/postgresql/data

volumes:
  db:
    driver: local

